### ISSUE TITLE
Error detected

### ISSUE THREAD

**Issue by tsonglew** [neo1218/MuxiVim#4]
After being installed,it cannot function properly.
the code 'vim' still lead to the original vim but not MuxiVim

with the Error:
        line 95:
        E185: Cannot find color scheme 'wombat256mod'
        line 186:
        E117: Unknown function: pathogen#infect

**Comment by misakar** [comment]
Thanks for bug report, can you tell me more about your vim version and install environment?

**Comment by tsonglew** [comment]
vim 7.4.52
ubuntu

**Comment by misakar** [comment]
~the code 'vim' still lead to the original vim but not MuxiVim~
what this ~original vim~ version?

**Comment by tsonglew** [comment]
the one without any decoration,showing the slogan 'help poor children in Uganda'

**Comment by misakar** [comment]
just <code>rm -rf ~/.vim</code> and reinstall MuxiVim.
