### ISSUE TITLE
ubuntu下tmux与vim同时运行vim样式错误

### ISSUE THREAD

**Issue by tsonglew** [neo1218/MuxiVim#5]
ubuntu下tmux与vim同时运行vim样式错误

**Comment by misakar** [comment]
你在~/.tmux.conf 加上这行 <code>set -g default-terminal "screen-256color"
</code> 试试

**Comment by tsonglew** [comment]
并没有用。。。。。

**Comment by misakar** [comment]
好

**Comment by misakar** [comment]
你试试 tmux -2 new -s "test" (用tmux -2启动tmux 试试)

**Comment by tsonglew** [comment]
OK~
